---
- block:
    - name: Run service facts
      service_facts:

    - name: Drain and stop the node before restart
      block:
        - name: Get node status
          shell: 
            cmd: nodetool status
          ignore_errors: yes
          register: nodetool_status

        - name: Run nodetool drain
          shell: 
            cmd: nodetool drain
          ignore_errors: yes

        - name: Restart service
          service:
            name: "{{ cassandra_service_name }}"
            state: restarted
            enabled: yes
      when: ansible_facts.services[cassandra_service_name].state == 'running'

    - name: Start the service
      service:
        name: "{{ cassandra_service_name }}"
        state: started
        enabled: yes
      when: ansible_facts.services[cassandra_service_name].state in ['failed', 'stopped']

    - name: Ensure service is up and running
      wait_for:
        path: "{{ cassandra_log_dir }}/system.log"
        search_regex: Startup complete
        delay: 10
        timeout: 120

    - name: Ensure JMX port is listening
      wait_for:
        host: 127.0.0.1
        port: 7199
        delay: 10
        timeout: 120
  when: inventory_hostname == item
  tags: molecule-idempotence-notest
