---
- name: Prepare
  hosts: all
  gather_facts: no

  pre_tasks:
    - name: Wait for SSH
      wait_for_connection:

    - name: Gather facts for first time
      setup:

    - name: Install python for Ansible
      apt: 
        name: "{{ item.packages }}"
        update_cache: yes
      become: true
      when: item.dist == ansible_distribution_release
      loop:
        - dist: focal
          packages: 
            - python3-apt
        - dist: bionic
          packages:
            - python-minimal
            - python-apt

  roles:
    - name: gantsign.java
      vars:
        java_version: 8.0.302+8
        java_use_local_archive: no
        java_is_default_installation: yes
      tags: ['dependencies', 'java']

  post_tasks:
    - name: Ensure correct java version is selected
      alternatives:
        link: /usr/bin/java
        name: java
        path: "{{ ansible_local.java.general.home }}/bin/java"
        priority: 1
      become: yes
