---
- hosts: cassandra
  become: yes
  gather_facts: yes

  tasks:
    - name: Run nodetool status
      shell: 
        cmd: nodetool status
      register: nodetool_status
      until: nodetool_status is succeeded
      retries: 5
      delay: 10

    - name: Debug
      debug:
        msg:
          "nodetool_status": "{{ nodetool_status.stdout_lines }}"
